api_platform:
  title: "Underwater API"
  description: "A Symfony API to manage Underwater project."
  metadata_backward_compatibility_layer: false
  version: "1.0.0"
  mapping:
    paths: ["%kernel.project_dir%/src/Entity"]
  patch_formats:
    json: ["application/merge-patch+json"]
  swagger:
    api_keys:
      JWT:
        name: Authorization
        type: header
