controllers:
  resource: ../src/Controller/
  type: attribute
authentication_token:
  path: /api/login
  methods: ["POST"]
api_refresh_token:
  path: /api/refresh_token
api_graphql_entrypoint:
  path: /api/graphql
  controller: api_platform.graphql.action.entrypoint
